### ISSUE TITLE
Identifying apps with other way than the title

### ISSUE THREAD

**Issue by AmkSk** [pierrechevalier83/workstyle#11]
Hello, I have noticed that a lot of apps do not contain their name in the title. For example Spotify is called "Spotify Premium" when nothing is playing and "{artist} - {song}" when playing something. I cannot identify the app this way and so there is no icon for the workspace.

Is there any other way how to identify apps?

**Comment by rYR79435** [comment]
duplicate of/related to #6

**Comment by pierrechevalier83** [comment]
This is a duplicate of #6

**Comment by wjdp** [comment]
(this has little to do with this project, the issue is with spotify but adding a note here for the next person who finds this topic)

For the specific Spotify issue it's worse as they don't set a class or app_id. This has been raised directly and perhaps they'll be a fix soon: https://community.spotify.com/t5/Desktop-Linux/No-window-icon-in-Wayland-because-app-id-is-not-correctly-set/m-p/6248728#M22919
