### ISSUE TITLE
Hyprland: Icon remains when moving window to another screen

### ISSUE THREAD

**Issue by cloudlena** [pierrechevalier83/workstyle#54]
When using Hyprland, I see the following issue:

1. Have a multi monitor setup.
1. Open a window on one monitor. The correct icon is displayed in Waybar using Workstyle.
1. Move the window to a workspace on another monitor using `movetoworkspace`.
1. The icon remains on the now empty workspace on the previous monitor.

For me, this issue is not reproducible on Sway. There, the now empty workspace correctly doesn't display a remnant icon.

**Comment by pierrechevalier83** [comment]
Thanks so much for the detailed report. I was able to reproduce it.

The problem happened when a workspace became empty as the result of a window move, because the way I was creating the list of workspaces to rename was by listing the windows and grouping them by the workspaces they belonged to. That omitted empty workspaces. I've fixed it on main now.

@cloudlena, could you try the latest main and confirm whether the issue is resolved for you now?

**Comment by cloudlena** [comment]
Thanks, @pierrechevalier83! The issue is indeed fixed :tada:
